server:
  port: 9010
spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      uri: "mongodb://mongo:qrgbYSzSHej053taZFJp@containers-us-west-200.railway.app:6246"
      database: "Kotlin"
      username: "mongo"
      password: "qrgbYSzSHej053taZFJp"
